name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
      - name: Install pybind11
        run: |
          sudo apt install -y cmake python3-dev libeigen3-dev libboost-dev git
          git clone https://github.com/pybind/pybind11.git
          cd pybind11
          cmake -DDOWNLOAD_CATCH=1
          mkdir build
          cd build
          cmake ..
          sudo make install
          cd ..
      - name: Build package
        run: |
          pip install -e .