name: build

on: [push]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.8','3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Build package 
        run: |
          python -m pip install -e .
      - name: Test 
        run: |
          python -m pip install --upgrade pytest
          pytest -v