name: build

on: [push]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Get conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          conda install -c conda-forge pybind11
      - name: Build package 
        run: |
          python3 -c "from pybind11.setup_helpers import Pybind11Extension, build_ext"
          python3 -m pip install -e .